#!/bin/bash
set -e

GITHUB_TOKEN=$1

# create the release
# curl \
#   -X POST \
#   -H 'Content-Type: application/json' \
#   --data '{
#   "tag_name": "0",
#   "target_commitish": "master",
#   "name": "0",
#   "body": "Version 0",
#   "draft": false,
#   "prerelease": false}
# ' https://api.github.com/repos/AlexChesters/utils/releases?access_token=$GITHUB_TOKEN

# upload the RPM to the release
curl \
  -X POST \
  -H 'Content-Type: application/x-rpm' \
  --data @RPMS/x86_64/alexchesters-utils-0.0.0-1.x86_64.rpm \
  https://api.github.com/repos/AlexChesters/utils/releases/11852688/assets?access_token=$GITHUB_TOKEN&name=alexchesters-utils.rpm
